messages:
  prefix: ''
  no_permission: '&8&l[&C&l!&8&l] &cNie możesz używać tego polecenia'
  server_connect: '&7Trwa laczenie do &f%server%'
  server_offline: '&8&l[&C&l!&8&l] &clobby jest obecnie offline'
  server_already_connected: '&8&l[&C&l!&8&l] &cJestes juz polaczony z tym lobby'

# Aby dodać nowy serwer uzyj następującego szablonu:

# przykład-serwera: lobby_01 # Nazwa serwera w bungeecord config.yml
# host: 127.0.0.1 # adres IP serwera
# port: 25565 # Port serwera.
# displayname: lobby_01 # Nazwa widoczna w lore w gui
# slot: 0 # Slot iventory, na którym ma się znaleźć dany przedmiot w gui

inventory:
  rows: 3
  title: '&7Zmiana &8(&fKanalu&8)'

servers:
  lobby_01:
    host: 127.0.0.1
    port: 25565
    displayname: lobby1
    slot: 10
  lobby_02:
    host: 127.0.0.1
    port: 25565
    displayname: lobby2
    slot: 11

layouts:
  online:
    material: STAINED_CLAY
    subid: 5
    glow: true
    displayname: '&a%server%'
    lore:
      - ' &8> &7Status &aonline&8.'
      - ' &8> &7Graczy &8: &f%players%'
      - ''
      - ' &8» &aKliknij aby polaczyc sie na serwer'
  offline:
    material: REDSTONE
    subid: 0
    glow: true
    displayname: '&c%server%'
    lore:
      - ' &8> &7Status: &4offline&8.'
      - ' &8> &7Graczy &8: &f0'
  current:
    material: STAINED_CLAY
    subid: 4
    glow: true
    displayname: '&a%server%'
    lore:
      - ' &8> &7Status &aonline&8.'
      - ' &8> &7Graczy &8: &f%players%'
      - ''
      - ' &8> &cJestes juz polaczony z tym lobby!&8.'

hotbarItem:
  material: WATCH
  subid: 0
  displayname: '&7Zmiana &8(&fKanalu&8)'
  lore: []
  slot: 5

